#!/usr/bin/env python

'''
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, version 3.
 This program is distributed in the hope that it will be useful, but
 WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 General Public License for more details.
 You should have received a copy of the GNU General Public License
 along with this program. If not, see <http://www.gnu.org/licenses/>.
'''

import cv2, numpy
from argparse import ArgumentParser

parser = ArgumentParser(description='EscapeRoom server')
parser.add_argument(
    '--src', type=str, default='/dev/video0', help='Source video'
    )
args = parser.parse_args()

import picamera

with picamera.PiCamera() as camera:
    camera.resolution = (1024,1024)
    camera.shutter_speed = 12562
    camera.awb_gains = (155/128, 181/64)
    camera.awb_mode = 'off'

    camera.start_recording('video.h264')

    camera.wait_recording(5) #wait for angalog_gain and digital_gain to settle
    awb_gains = camera.awb_gains
    camera.exposure_mode = 'off'
    camera.awb_gains = awb_gains

    for i in range(60):
        camera.wait_recording(1)
    camera.stop_recording()
